package utils

import (
	"encoding/json"
	"strings"

	"github.com/invopop/jsonschema"
)

// BuildLLMStructure generates a JSON Schema from a simplified JSON description.
// This is optimized for OpenAI's strict mode requirements (Structured Outputs).
func BuildLLMStructure(input string) (string, error) {
	var raw interface{}
	if err := json.Unmarshal([]byte(input), &raw); err != nil {
		return "", err
	}

	// Convert the raw description into a standard JSON Schema
	schema := convertToSchema(raw)

	// Set a default description for the root node
	schema.Description = "Generated by dynamic extractor"

	data, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// convertToSchema recursively converts a generic value into a JSON Schema.
func convertToSchema(value interface{}) *jsonschema.Schema {
	schema := &jsonschema.Schema{}

	switch v := value.(type) {
	case string:
		primaryType, enums := parseTypeAndEnum(v)
		schema.Type = normalizeType(primaryType)
		if len(enums) > 0 {
			schema.Enum = make([]interface{}, len(enums))
			for i, e := range enums {
				schema.Enum[i] = e
			}
		}
	case map[string]interface{}:
		schema.Type = "object"
		// OpenAI requirement: disable additional properties for strict mode
		schema.AdditionalProperties = jsonschema.FalseSchema
		schema.Properties = jsonschema.NewProperties()

		for key, val := range v {
			prop := convertToSchema(val)
			schema.Properties.Set(key, prop)
			// OpenAI recommendation: make all fields required in extraction scenarios
			schema.Required = append(schema.Required, key)
		}
	case []interface{}:
		schema.Type = "array"
		if len(v) > 0 {
			schema.Items = convertToSchema(v[0])
		} else {
			// Default to string items for empty arrays to prevent errors
			schema.Items = &jsonschema.Schema{Type: "string"}
		}
	}
	return schema
}

// normalizeType maps common type names to standard JSON Schema types.
func normalizeType(typeName string) string {
	typeName = strings.ToLower(strings.TrimSpace(typeName))

	// Handle descriptive information in parentheses
	if index := strings.IndexAny(typeName, " (（"); index != -1 {
		typeName = typeName[:index]
	}

	switch typeName {
	case "int", "integer", "long":
		return "integer"
	case "float", "double", "number":
		return "number"
	case "bool", "boolean":
		return "boolean"
	case "arr", "array", "list":
		return "array"
	case "obj", "object", "map":
		return "object"
	default:
		return "string"
	}
}

// parseTypeAndEnum extracts the primary type and enum values from a string like "string enum(a,b,c)".
func parseTypeAndEnum(input string) (string, []string) {
	input = strings.TrimSpace(input)
	start := strings.Index(input, "enum(")
	if start == -1 {
		return input, nil
	}
	end := strings.LastIndex(input, ")")
	if end == -1 || end <= start+5 {
		return input, nil
	}

	primaryType := strings.TrimSpace(input[:start])
	enumString := input[start+5 : end]
	parts := strings.Split(enumString, ",")
	enums := make([]string, 0, len(parts))
	for _, part := range parts {
		enums = append(enums, strings.TrimSpace(part))
	}
	return primaryType, enums
}
